name: blind_scoring
channels:
  - conda-forge
  - defaults
dependencies:
  - aom=3.9.1
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - cairo=1.16.0
  - dav1d=1.2.1
  - expat=2.7.1
  - fontconfig=2.14.1
  - freetype=2.13.3
  - fribidi=1.0.16
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icu=73.2
  - jpeg=9e
  - lcms2=2.16
  - lerc=4.0.0
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libavif=1.3.0
  - libavif16=1.3.0
  - libcxx=19.1.7
  - libdeflate=1.22
  - libffi=3.4.4
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libglib=2.84.2
  - libiconv=1.18
  - libintl=0.25.1
  - libintl-devel=0.25.1
  - libpng=1.6.39
  - libtiff=4.7.0
  - libwebp-base=1.6.0
  - libxml2=2.13.8
  - lz4-c=1.9.4
  - ncurses=6.5
  - openjpeg=2.5.2
  - openssl=3.5.4
  - pcre2=10.42
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - python=3.12.11
  - rav1e=0.7.1
  - readline=8.3
  - setuptools=78.1.1
  - sqlite=3.50.2
  - svt-av1=3.1.2
  - tk=8.6.15
  - tzdata=2025b
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
    - numpy==2.2.6
    - opencv-python==4.12.0.88
